name: Deploy to Storefrontcloud
on:
  push:
    branches:
      - feat/hide-theme-and-cloud-deploy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Build packages
        run: |
          yarn
          yarn build --ci
      - name: Create theme project
        run: |
          mkdir test-project
          cd ./test-project
          ../packages/cli/bin/shopware-pwa init
          yarn build
          cd ../
      - name: Build and publish docker image
        uses: mr-smithers-excellent/docker-build-push@v2
        with:
          image: registry.storefrontcloud.io/shopware-pwa-storefrontcloud-io/vue-storefront
          tag: master
          registry: registry.storefrontcloud.io
          dockerfile: ./test-project/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # - name: Build docker image
      #   run: |
      #     cd ./test-project
      #     docker login registry.storefrontcloud.io
      #     yarn build
      #     cd ../
      # - name: Publish to Registry
      #   uses: HurricanKai/Publish-Docker-Github-Action@master
      #   with:
      #     name: registry.storefrontcloud.io/shopware-pwa-storefrontcloud-io/vue-storefront:master
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     registry: registry.storefrontcloud.io
      - name: Deploy on cloud
        run: |
          curl -u ${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }} -H 'Content-Type: application/json' -X POST -d '{"code":"shopware-pwa","frontContainerVersion":"master"}' https://farmer.storefrontcloud.io/instances
